
package view;

import controller.DestinasiController;
import controller.UserController;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;


public class HomePengunjung extends javax.swing.JFrame {
    private JTable tableRatingUlasan;

    public HomePengunjung() {
        initComponents();        
        tableRatingUlasan = new JTable(new DefaultTableModel(
        new Object[]{"Nama Destinasi", "Rating", "Ulasan", "Tanggal"}, 0));
        
        DestinasiController crudController = new DestinasiController(jTableDataWisata);
        crudController.read();
        
        setLocationRelativeTo(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxSorting = new javax.swing.JComboBox<>();
        jTextFieldPencarian = new javax.swing.JTextField();
        jToggleButtonOK = new javax.swing.JToggleButton();
        jToggleButtonKembali = new javax.swing.JToggleButton();
        jToggleButtonLihatRatingUlasan = new javax.swing.JToggleButton();
        jToggleButtonSegarkanData = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataWisata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxSorting.setBackground(new java.awt.Color(244, 229, 218));
        jComboBoxSorting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxSorting.setForeground(new java.awt.Color(50, 81, 118));
        jComboBoxSorting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wisata Berdasarkan Harga Tertinggi", "Wisata Berdasarkan Harga Terendah", "Wisata Berdasarkan Abjad A-Z" }));
        jComboBoxSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSortingActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxSorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 220, 30));
        getContentPane().add(jTextFieldPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, 30));

        jToggleButtonOK.setText("OK");
        jToggleButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, 30));

        jToggleButtonKembali.setBackground(new java.awt.Color(50, 81, 118));
        jToggleButtonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonKembali.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonKembali.setText("Kembali");
        jToggleButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 80, 30));

        jToggleButtonLihatRatingUlasan.setBackground(new java.awt.Color(50, 81, 118));
        jToggleButtonLihatRatingUlasan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonLihatRatingUlasan.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonLihatRatingUlasan.setText("Lihat Rating Ulasan");
        jToggleButtonLihatRatingUlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLihatRatingUlasanActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonLihatRatingUlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 170, -1));

        jToggleButtonSegarkanData.setBackground(new java.awt.Color(244, 229, 218));
        jToggleButtonSegarkanData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonSegarkanData.setForeground(new java.awt.Color(50, 81, 118));
        jToggleButtonSegarkanData.setText("Segarkan Data");
        jToggleButtonSegarkanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSegarkanDataActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonSegarkanData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 170, -1));

        jPanel1.setBackground(new java.awt.Color(244, 229, 218));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(244, 229, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(50, 81, 118));
        jLabel2.setText("Pengelola Wisata Terbaik di Samarinda yang Pastinya Akan Membantumu Untuk Mencari Destinasi Wisata.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(50, 81, 118));
        jLabel3.setText("Selamat Datang di PASTI!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jTableDataWisata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Destinasi", "Jam Operasional", "Deskripsi", "Lokasi", "Fasilitas", "HTM"
            }
        ));
        jTableDataWisata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDataWisataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDataWisata);
        if (jTableDataWisata.getColumnModel().getColumnCount() > 0) {
            jTableDataWisata.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableDataWisata.getColumnModel().getColumn(5).setPreferredWidth(25);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 680, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 700, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundDefault2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonLihatRatingUlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLihatRatingUlasanActionPerformed
        int selectedRow = jTableDataWisata.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih destinasi terlebih dahulu!");
            return;
        }
        
        String namaDestinasi = jTableDataWisata.getValueAt(selectedRow, 0).toString();
        tableRatingUlasan.setName(namaDestinasi);

        if (tableRatingUlasan == null) {
            JOptionPane.showMessageDialog(this, "Tabel Rating dan Ulasan belum diinisialisasi!");
            return;
        }
        
        MenuPengunjung menupengunjung = new MenuPengunjung(namaDestinasi, false);
        menupengunjung.setVisible(true);
        HomePengunjung.this.dispose();
    }//GEN-LAST:event_jToggleButtonLihatRatingUlasanActionPerformed

    private void jToggleButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonKembaliActionPerformed
        UserController.clearSession();
        MainHome mainhome = new MainHome();
        mainhome.setVisible(true);
        HomePengunjung.this.dispose();
    }//GEN-LAST:event_jToggleButtonKembaliActionPerformed

    private void jComboBoxSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSortingActionPerformed
        String selectedOption = (String) jComboBoxSorting.getSelectedItem();

        if (selectedOption == null || selectedOption.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih metode penyortiran!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            ArrayList<Object[]> sortedDestinasi = DestinasiController.sortDestinasi(selectedOption);

            DefaultTableModel tableModel = (DefaultTableModel) jTableDataWisata.getModel();
            tableModel.setRowCount(0);

            for (Object[] data : sortedDestinasi) {
                tableModel.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxSortingActionPerformed

    private void jTableDataWisataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDataWisataMouseClicked
        int row = jTableDataWisata.getSelectedRow();
        if (row != -1) {
            String namaDestinasi = jTableDataWisata.getValueAt(row, 0).toString();
            String jamOperasional = jTableDataWisata.getValueAt(row, 1).toString();
            String deskripsi = jTableDataWisata.getValueAt(row, 2).toString();
            String lokasi = jTableDataWisata.getValueAt(row, 3).toString();
            String fasilitas = jTableDataWisata.getValueAt(row, 4).toString();
            int biayaMasuk = Integer.parseInt(jTableDataWisata.getValueAt(row, 5).toString());
        }
    }//GEN-LAST:event_jTableDataWisataMouseClicked

    private void jToggleButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOKActionPerformed
        String namaDestinasi = jTextFieldPencarian.getText().trim();

        if (namaDestinasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Masukkan nama destinasi untuk mencari!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nama Destinasi");
            model.addColumn("Lokasi");
            model.addColumn("Jam Operasional");
            model.addColumn("Deskripsi");
            model.addColumn("Fasilitas");
            model.addColumn("Biaya Masuk");
            jTableDataWisata.setModel(model);

            ArrayList<Object[]> destinasiList = DestinasiController.cariDestinasiWisata(namaDestinasi);

            if (destinasiList == null || destinasiList.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Tidak ada destinasi ditemukan untuk nama: " + namaDestinasi, 
                    "Info", 
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            for (Object[] destinasi : destinasiList) {
                System.out.println("");
                model.addRow(destinasi);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan saat mencari destinasi: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButtonOKActionPerformed

    private void jToggleButtonSegarkanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSegarkanDataActionPerformed
        DestinasiController controller = new DestinasiController(jTableDataWisata);
        controller.refreshData();
        JOptionPane.showMessageDialog(this, "Data berhasil disegarkan!");        
    }//GEN-LAST:event_jToggleButtonSegarkanDataActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSorting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDataWisata;
    private javax.swing.JTextField jTextFieldPencarian;
    private javax.swing.JToggleButton jToggleButtonKembali;
    private javax.swing.JToggleButton jToggleButtonLihatRatingUlasan;
    private javax.swing.JToggleButton jToggleButtonOK;
    private javax.swing.JToggleButton jToggleButtonSegarkanData;
    // End of variables declaration//GEN-END:variables

    private void table() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

