package view;

import controller.DestinasiController;
import controller.UserController;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;

public class HomeAdmin extends javax.swing.JFrame {

    public HomeAdmin() {
        initComponents();
        DestinasiController crudController = new DestinasiController(jTableDataWisata); 
        crudController.read();
        
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxSorting = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataWisata = new javax.swing.JTable();
        jToggleButtonLihatRatingUlasan = new javax.swing.JToggleButton();
        Pencarian = new javax.swing.JTextField();
        jToggleButtonOK = new javax.swing.JToggleButton();
        jToggleButtonKelolaDestinasiWisata = new javax.swing.JToggleButton();
        jToggleButtonKeluar = new javax.swing.JToggleButton();
        jToggleButtonSegarkanData = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 81, 118));

        jComboBoxSorting.setBackground(new java.awt.Color(249, 222, 181));
        jComboBoxSorting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxSorting.setForeground(new java.awt.Color(50, 81, 118));
        jComboBoxSorting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wisata Berdasarkan Harga Tertinggi", "Wisata Berdasarkan Harga Terendah", "Wisata Berdasarkan Abjad A-Z" }));
        jComboBoxSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSortingActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Halo, Admin!");
        jLabel2.setPreferredSize(new java.awt.Dimension(72, 16));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengelolaan Destinasi Wisata di Samarinda.");
        jLabel3.setPreferredSize(new java.awt.Dimension(72, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 220, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxSorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxSorting, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 700, 90));

        jTableDataWisata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Destinasi", "Jam Operasional", "Deskripsi", "Lokasi", "Fasilitas", "HTM"
            }
        ));
        jScrollPane1.setViewportView(jTableDataWisata);
        if (jTableDataWisata.getColumnModel().getColumnCount() > 0) {
            jTableDataWisata.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableDataWisata.getColumnModel().getColumn(5).setPreferredWidth(25);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 700, 170));

        jToggleButtonLihatRatingUlasan.setBackground(new java.awt.Color(50, 81, 118));
        jToggleButtonLihatRatingUlasan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonLihatRatingUlasan.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonLihatRatingUlasan.setText("Lihat Rating dan Ulasan");
        jToggleButtonLihatRatingUlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLihatRatingUlasanActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonLihatRatingUlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 170, -1));
        getContentPane().add(Pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 320, 30));

        jToggleButtonOK.setText("OK");
        jToggleButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOKActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 30));

        jToggleButtonKelolaDestinasiWisata.setBackground(new java.awt.Color(50, 81, 118));
        jToggleButtonKelolaDestinasiWisata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonKelolaDestinasiWisata.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonKelolaDestinasiWisata.setText("Kelola Destinasi Wisata");
        jToggleButtonKelolaDestinasiWisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonKelolaDestinasiWisataActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonKelolaDestinasiWisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 230, 30));

        jToggleButtonKeluar.setBackground(new java.awt.Color(50, 81, 118));
        jToggleButtonKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonKeluar.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonKeluar.setText("Keluar");
        jToggleButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 80, 30));

        jToggleButtonSegarkanData.setBackground(new java.awt.Color(249, 222, 181));
        jToggleButtonSegarkanData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonSegarkanData.setForeground(new java.awt.Color(50, 81, 118));
        jToggleButtonSegarkanData.setText("Segarkan Data");
        jToggleButtonSegarkanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSegarkanDataActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonSegarkanData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundDefault.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSortingActionPerformed
        String selectedOption = (String) jComboBoxSorting.getSelectedItem();

        if (selectedOption == null || selectedOption.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silakan pilih metode penyortiran!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            ArrayList<Object[]> sortedDestinasi = DestinasiController.sortDestinasi(selectedOption);

            DefaultTableModel tableModel = (DefaultTableModel) jTableDataWisata.getModel();
            tableModel.setRowCount(0);

            for (Object[] data : sortedDestinasi) {
                tableModel.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jComboBoxSortingActionPerformed

    private void jToggleButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonKeluarActionPerformed
        UserController.clearSession();
        MainHome mainhome = new MainHome();
        mainhome.setVisible(true);
        HomeAdmin.this.dispose();
    }//GEN-LAST:event_jToggleButtonKeluarActionPerformed

    private void jToggleButtonKelolaDestinasiWisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonKelolaDestinasiWisataActionPerformed
        MenuAdmin menuadmin = new MenuAdmin();
        menuadmin.setVisible(true);
        HomeAdmin.this.dispose();
    }//GEN-LAST:event_jToggleButtonKelolaDestinasiWisataActionPerformed

    private void jToggleButtonLihatRatingUlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLihatRatingUlasanActionPerformed
        int selectedRow = jTableDataWisata.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih destinasi terlebih dahulu!");
            return;
        }
        
        String namaDestinasi = jTableDataWisata.getValueAt(selectedRow, 0).toString();
        MenuPengunjung menuPengunjung = new MenuPengunjung(namaDestinasi, true);
        menuPengunjung.setVisible(true);
        HomeAdmin.this.dispose();
    }//GEN-LAST:event_jToggleButtonLihatRatingUlasanActionPerformed

    private void jToggleButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOKActionPerformed
        String namaDestinasi = Pencarian.getText().trim();

        if (namaDestinasi.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Masukkan nama destinasi untuk mencari!", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nama Destinasi");
            model.addColumn("Lokasi");
            model.addColumn("Jam Operasional");
            model.addColumn("Deskripsi");
            model.addColumn("Fasilitas");
            model.addColumn("Biaya Masuk");
            jTableDataWisata.setModel(model);

            ArrayList<Object[]> destinasiList = DestinasiController.cariDestinasiWisata(namaDestinasi);

            if (destinasiList == null || destinasiList.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Tidak ada destinasi ditemukan untuk nama: " + namaDestinasi, 
                    "Info", 
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            for (Object[] destinasi : destinasiList) {
                System.out.println("");
                model.addRow(destinasi);
            }
        } catch (Exception ex) {
            ex.printStackTrace();

            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan saat mencari destinasi: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButtonOKActionPerformed

    private void jToggleButtonSegarkanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSegarkanDataActionPerformed
        DestinasiController controller = new DestinasiController(jTableDataWisata);
        controller.refreshData();
        JOptionPane.showMessageDialog(this, "Data berhasil disegarkan!");        
    }//GEN-LAST:event_jToggleButtonSegarkanDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pencarian;
    private javax.swing.JComboBox<String> jComboBoxSorting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDataWisata;
    private javax.swing.JToggleButton jToggleButtonKelolaDestinasiWisata;
    private javax.swing.JToggleButton jToggleButtonKeluar;
    private javax.swing.JToggleButton jToggleButtonLihatRatingUlasan;
    private javax.swing.JToggleButton jToggleButtonOK;
    private javax.swing.JToggleButton jToggleButtonSegarkanData;
    // End of variables declaration//GEN-END:variables
}
