package view;

import controller.RatingUlasanController;
import model.UserModel;
import controller.UserController;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;

public class MenuPengunjung extends javax.swing.JFrame {
    private JTable jTableDataWisata;
    private String namaDestinasi;
    
    public MenuPengunjung(String namaDestinasi, boolean isAdmin) {
        this.namaDestinasi = namaDestinasi;
                
        initComponents();
        
        jTableRatingUlasan = new JTable(new DefaultTableModel(
                new Object[]{"Nama Destinasi", "Rating", "Ulasan", "Tanggal"}, 0));
        
        jTableDataWisata = new JTable(new DefaultTableModel(
                new Object[]{"Nama Destinasi", "Jam Operasional", "Deskripsi", "Lokasi", "Fasilitas", "Biaya Masuk"}, 0));  
        
        RatingUlasanController.loadUlasanToTable(jTableRatingUlasan, namaDestinasi);
        jScrollPane1.setViewportView(jTableRatingUlasan);
        
        if (isAdmin) {
            inputRating.setVisible(false);
            inputBerikanUlasan.setVisible(false);
            jToggleButtonBuatRatingUlasan.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            
            setLocationRelativeTo(this);
        }
    }

    MenuPengunjung(String username, String namaDestinasi) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRatingUlasan = new javax.swing.JTable();
        jToggleButtonKembali = new javax.swing.JToggleButton();
        inputRating = new javax.swing.JTextField();
        inputBerikanUlasan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButtonBuatRatingUlasan = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableRatingUlasan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Destinasi", "Ulasan", "Rating", "Tanggal Ulasan & Rating"
            }
        ));
        jTableRatingUlasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRatingUlasanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRatingUlasan);
        if (jTableRatingUlasan.getColumnModel().getColumnCount() > 0) {
            jTableRatingUlasan.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 680, 110));

        jToggleButtonKembali.setBackground(new java.awt.Color(50, 81, 118));
        jToggleButtonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonKembali.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonKembali.setText("Kembali");
        jToggleButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 140, -1));

        inputRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRatingActionPerformed(evt);
            }
        });
        getContentPane().add(inputRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 320, 30));
        getContentPane().add(inputBerikanUlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 320, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Berikan Rating");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Berikan Ulasan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jToggleButtonBuatRatingUlasan.setBackground(new java.awt.Color(249, 222, 181));
        jToggleButtonBuatRatingUlasan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButtonBuatRatingUlasan.setForeground(new java.awt.Color(50, 81, 118));
        jToggleButtonBuatRatingUlasan.setText("Buat Rating dan Ulasan");
        jToggleButtonBuatRatingUlasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBuatRatingUlasanActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonBuatRatingUlasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BackgroundDefault.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRatingActionPerformed

    private void jToggleButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonKembaliActionPerformed
        UserModel currentUser = UserController.getCurrentUser();
        if (currentUser != null && currentUser.getRole().equalsIgnoreCase("admin")) {
            HomeAdmin homeAdmin = new HomeAdmin();
            homeAdmin.setVisible(true);
        } else {
            HomePengunjung homePengunjung = new HomePengunjung();
            homePengunjung.setVisible(true);
        }
        MenuPengunjung.this.dispose();
    }//GEN-LAST:event_jToggleButtonKembaliActionPerformed

    private void jToggleButtonBuatRatingUlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBuatRatingUlasanActionPerformed
        String ulasan = inputBerikanUlasan.getText();
        String ratingText = inputRating.getText();

        if (ulasan.isEmpty() || ratingText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua kolom!");
            return;
        }

        try {
            int rating = Integer.parseInt(ratingText);
            if (rating < 1 || rating > 5) {
                JOptionPane.showMessageDialog(this, "Rating harus antara 1 hingga 5!");
                return;
            }
            
            UserModel currentUser = UserController.getCurrentUser();
            if (currentUser == null) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan ulasan. Pengguna tidak terautentikasi.");
                return;
            }
            
            int id_user = currentUser.getId_user();

            RatingUlasanController ratingUlasan = new RatingUlasanController(jTableRatingUlasan);
            if (ratingUlasan.createRatingUlasan(namaDestinasi, rating, ulasan, id_user)) {
                JOptionPane.showMessageDialog(this, "Ulasan berhasil disimpan!");
                inputBerikanUlasan.setText("");
                inputRating.setText("");
                RatingUlasanController.loadUlasanToTable(jTableRatingUlasan, namaDestinasi);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan ulasan.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Rating harus berupa angka!");
        }
    }//GEN-LAST:event_jToggleButtonBuatRatingUlasanActionPerformed

    private void jTableRatingUlasanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRatingUlasanMouseClicked

    }//GEN-LAST:event_jTableRatingUlasanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new MenuPengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputBerikanUlasan;
    private javax.swing.JTextField inputRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRatingUlasan;
    private javax.swing.JToggleButton jToggleButtonBuatRatingUlasan;
    private javax.swing.JToggleButton jToggleButtonKembali;
    // End of variables declaration//GEN-END:variables

    private void table() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
